-- Copermiq — rol de administrador
--
-- ⚠️ EN PAUSA — NO APLICAR TODAVÍA (ni con `supabase db push` ni pegando
-- esto en el SQL Editor).
--
-- La tabla `profiles` real la gestiona también el lado de la app
-- (verificado el 2026-08-08: usa `user_id`, no `id`, y no tiene ninguna
-- columna de "es administrador" — el panel de admin de la app resuelve
-- eso ahora mismo con un email fijo en su propio código). Antes de añadir
-- esta columna hay que coordinar con ese lado cómo se va a marcar a
-- alguien como administrador de forma compartida, para no acabar con dos
-- conceptos de "admin" distintos (uno en código de la app, otro aquí en
-- una columna). Ver copermiq-billing-architecture.md.
--
-- Si en algún momento se decide seguir por este camino (una columna
-- `role` compartida), aplicar esto:
--
--   alter table public.profiles
--     add column if not exists role text not null default 'user'
--       check (role in ('user', 'admin'));
--
-- Y para marcar a alguien como admin (con el nombre de columna real):
--
--   update public.profiles set role = 'admin' where user_id = '<uuid del usuario>';
--   -- para encontrar el uuid: select id from auth.users where email = '...';
